### ISSUE TITLE
Proper ate-contract interaction

### ISSUE THREAD

**Issue by androlo** [eris-ltd/decerver#95] opened 2015-01-25 01:59 UTC
I've been talking about this for a while, and worked on it. Ate-to-UI has just taken a huge leap forward when we added the RESTful API, and with some updates to websockets that will also be a lot more clear. I would even dare to call it production ready after these changes has been properly worked in, which will not be after the video dapp, but probably after the next few dapps we write. Ate-to-contracts interaction, however, is not good. These are some of the issues:

1) The "system" I/we use for calling contracts from Ate has not been standardized. 

2) The "system" I/we use for doing automated tests of contracts from Ate has not been standardized.

3) The "system" we use to frame smart contract back-ends has not been standardized. C3D has not been implemented in ate, nor any other system that's similar.

4) Contract code documentation has not been standardized.

Solutions are coming. The changes I'm working on now are significant. I've been working on a document about systems of contracts. It involves C3D and some other things. It is still not done, and will not be done in some time, but it will be a good source of information about how to write systems of contract in general (pointing out different types of contracts and their usage). It will also be useful for ethereum contract writers since it does not really depend on anything external. 

There will also be another document which will use that document but treat these type of things, like json specs, testing, documenting etc. It'll be the stuff in the first document applied in the Eris system, you could say. This issue will be the basis for that document.

**Contracts, EPM and Ate**

I don't like the fact that DApp devs are forced to work with two systems - both ate and epm. That is a source of confusion, even for me. Instead, when epm is wrapped by the decerver, it will be possible to do it all from ate. Same interface for everything (js), and the same system for everything. EPM is a stand-alone library anyways, so using Ate as a front does not mean it can't be used by people who want more low-level control.

Also, I don't like that we include LLL contracts in tutorial examples. This also needs to change, and it should happen soon. We're working on it. For example, Ethan has started adding support for and otherwise enabling the use of other languages in his LLLC compiler, and there has been changes to EPM and Thelonious as well.

When it comes to languages, Serpent will likely be a placeholder for some time, but it looks like Solidity will be the best alternative for dapp makers in the long run. It's worked on by several, seemingly competent people, it's coming along nicely, it's clean, it's got very nice features, it's similar to js (which we use in other parts of the stack), and other things. This together with the heavy backing from Ethereum means it will likely become the lingua franca for contract developers, so we might as well jump on board imo.

*One language to rule them all, one language as placeholder, one language to drag out into the backyard, and in the darkness shoot it, bury it, and forget about it.*

**Contract specifications**

Ate will support a standardized model for contracts. The specs are written in JSON, and will look something like this:

``` javascript
Contract
{
	"name" : String,
	"constants" : {
		"const1" : String,
		"const2" : String,
		...
	},
	"functions" : {
		"func1" : Function,
		"func2" : Function,
		...
	}
}

Function
{
	"id" : Number,
	"params" : [Variable],
	"returns" : [Variable]
}

Variable 
{
	"name" : String,
	"type" : Type,
	"size" : Number
}
```

An example would be the hello world tutorial contract "test.lll", which would look something like this:

``` javascript
Hello world:
{
	"name" : helloworld,
	"variables" : { "deadbeef" : "0x10" },
	"functions" : {
		"register" : {
			"id" : 0,
			"params" : [{"name" : username, "type" : String, "size", 32}] 
		}
	}
}
```

You should probably be able to specify dependencies as well, and ate should be able to write the contract in full, based on these dependencies. I have already made a system for this. Basically it writes the properties of the dependencies from the dependency to the contract, but need to make it a bit more sophisticated to handle diamonds of death etc.

When it comes to 'type' - types here refer to data written into contract storage. There will be built-in types, but there will also be possible to specify custom types. Interaction with contracts, such as calls, reads, and automated tests can makes use of them to get a form of type-safety. A good example of when a type is needed is arrays and linked lists. When you write an array or linked list into storage, they are just a bunch of detached entries. It does not say anywhere in storage that "the following few addresses are part of a linked list". Ate, however, can use the contract spec to figure out that it is reading from an array or linked list, or in fact any other possible data structure, and also in the case of collections - what the elements are.

Ok so that's fine, but what about contract reading from contracts. Wouldn't they need to know? Yes, but data structures has been introduced to most languages at this point, so such things would be resolved during compile time. If your contract has a 'getElement' function, it would just return the elements as a data structure. The system I'm talking about here is for the reading of contract storage by ate. Technically it could call that 'getElement' function in the contract and get it that way (at least after some vm improvements?), but it would not just require waiting for a tx, which is annoying, but also a series of gas-guzzling in-contract storage reads where none are needed.

This sounds like an ate thing, but it really is not. These specs could be used by other systems as well, since they're just json files. They should also be done in collaboration between contract writers/platform makers, so that we get a good standard that everyone is happy with. I hope for examples that epm can use those contract specs as well, if they would be needed for something. Maybe even other platforms can make use of them.

Finally, note that these specs aren't like the project douglas action models. They don't contain any actual logic. They're just a description of what functions and pre-set variable slots that the contract uses. Action models would be built on top of these. There will be more on action models later.

**Testing contracts**

First of all - when we're talking about tests, we're always talking about testing against the database. Some clients lets you get the value that the vm returns as a result of executing the contract code, which can be useful, but not all clients allow that. Writing results to storage is a safe way of doing things, and every client out there supports it. If some functionality of a contract does not produce an entry in some database by default, then we can complement it with an additional test contract.

**'A simple test example**

This is a simple test of a contract which is designed to be called by other contracts, and does not make use of its own storage. Not gonna get into the details of what is written where.

The contract takes a 32 byte hex string and checks how many unique bytes it has (maybe for some compression stuff or whatever). The string "aabb" would return 3 (null counts too). The string "acdbba" would return 5. We call that contract 'dupcheck'.

We add a test contract that we call 'dupcheck_test'. It will have three functions. The first one is passing values into its storage-writing routine to make sure it actually works. The second is to call 'dupcheck' N times with predefined values and check that the values that come back are the ones we expect. It will write the results to its storage, so that they can be read. The third function is just to set the address of the 'dupcheck' contract.

We will then add a javascript test file. It will do the following things:

1) Deploy the 'dupcheck' and 'dupcheck_test' contracts on a temporary test chain and commit. 

2) Make sure that both of the contracts exist on the chain after this. That can be done by adding identifiers in their storage as part of the init code.

3) Set the address of 'dupcheck' in the 'dupcheck_test' contract, and commit.

4) Make sure the address is properly set (check the storage).

5) Transact to 'dupcheck_test' in order to call its test functions. commit.

6) Check the results by reading the storage addresses of the test contract.

7) Present the test results, for example by printing.

Note that we would make use of the spec at points 2, 3, 4, 5 and 6. In 2 we will use the id field, which could be named "id" in the spec. In 3 we make use of the function that sets the dupcheck address. In 4 check the "dupcheck_address" field. In 5 we make use of the test function, and in 6 we check the test results variables.

This is a trivial example. A more sophisticated test could be working with several target contracts. Some could be calling other test contracts and act as the entry point of a full-on test suite.

**Documentation of contracts**

I have been working with something called 'natural docs' to produce documentation for contracts before, which i think is one candidate. It is fairly simple, cross platform (though you need perl support), and lets you write your documentation any way you like inside the code. Just make a spec and it will extract the comments and turn it into html docs, with indexing, searching - everything. You can even create a script to auto generate documentation based on function sigs and other things. 

An example of this can be found here, in my old (abandoned) LLL-commons library:  https://github.com/androlo/LLL-commons. You can download and view the documentation at doc/lll/index.html, and check that it matches the documentation in the files.

**Finally**

This should be tied in with the action models and c3d documentation. It will be done in some later document that covers it all.

**Comment by dennismckinnon** [comment] 2015-01-25 03:12
I agree with much of this. However some of this i believe to be sub-optimal or slightly at cross purposes

First off I'll start with testing, Your framework does work. In fact its the current method I do testing. In particular I have a contract which performs a bunch of operations when testing a type template and then stores things in a manner which is easily check. EPM has the .pdt format which is explicitly designed for testing. It does not however require a secondary test contract as you can test against expected results directly.

Things its missing:
1) Does not allow for inspection of return results directly because thelonious and ethereum do not expose this. Personally I would be more in favour of modifying thelonious to expose return values higher up such that the .pdt can inspect them however this is not an easy thing to do as there is no "simulate" mode on the evm and the whole waiting for confirmation of a transaction makes things complicated here. That said I still believe a proper testing system involves a "simulate" functionality and interaction from where ate would normally be interacting and not a cobbled together secondary test function built on chain

2) Tests don't understand advanced storage types. I know you do not particularly like the type templates but from my point of view they offer far greater flexibility in what you design in smart contracts then any of the pre-built types alone with improved security. A good analogy for them is defining being able to define classes of objects whose interaction is predictable and configurable. Yes you can program without classes. but who really wants to. The issue is of course that I have defined a structure by which I want to fit data into the contracts in a replicatable manner. But the rules for doing so are more complex the "start here... add 1... add 1". I don't want to write contracts without these structures anymore but that causes a problem when reading externally in that these rules must be programmed somewhere. Right now that is in the form of the monk.js file. Having better integration and moving closer to a class-object design I feel is the better way to go and then designing a unit-test framework which can work with these definitions is far superior. In this ate's understanding of js written DB models files is possibly our greatest tool for unified testing.

If this can be combined with contract specifications I think we have something quite powerful. I do however (in relation to the above) think that the variables specification is too restrictive. One should never say "i'm storing this at slot 0xDEADBEEF" that is poor form if we are trying for higher level programming. What the templates have allowed you to do is say i have a variable called "owner" which is a single type. honestly because all of the variables store their type on chain along with their name you can reconstruct everything from the model and a name.

As for LLL versus Serpent for the language used in the demo dapps. To me it honestly does not matter except that if you want to re-write Youtube in Serpent then I will need help translating my templates to their framework which I'm happy to work with you on. I flat out refuse to write such a dapp without the templates as they allow me to place far more structure in a single contract then ever before making logic a snap. Once that is complete I am happy to re-write the dapp in Serpent and again when/if we switch to Solidarity.

With regard to backend contract frame work definitions. I'm in agreement 100% there however even C3D was not proficient at handling this. If we can come up with a self defining format for working with contract suites I am fully on board but this is not an easy feat due to the fluctuation nature of large contract suites. My initial thoughts on it is that either DOUG could act as a message forwarding service so only an outside API needs to be defined for the whole dapp and contracts register the forward with DOUG.

This unfortunately hits a snag when it comes to contract factories. A possible resolution to this is that the contract factory could register the API (or someone with doug permissions) that the created contracts accept and then handles forwarding of of messages. Each contract would need a unique identifier that could be passed to the factory contract so forwarding was unique.

In this framework all messaging passes through DOUG. The alternative is that each contract could self define its own API. This is somewhat fuzzy at this point but i think it is well worth investigating.

Using EPM just as a library has its advantages. but to be honest a clean and simple commandline interface is very appealing to me. I would not really want to boot up the decerver when i am manipulating chains. But I agree that Ate wrapped EPM is a must going forward.

Those are my thoughts on this. Lost of good points some things I think need tuning. but on the whole very good direction.

**Comment by androlo** [comment] 2015-01-25 05:00
Interesting, but a whole lot of "snags" and "ifs" and "buts" here, and dependence on things that does not exist, and maybe never will. This is something that'll be implemented tomorrow, not in a year, and therefore it will be fairly simple but scalable.

Yes you can test in epm, which may sound good, but that forces you to write a test file in a format that is not contract code, not javascript, but something entirely different that has its own (very strange) syntax and rules. Does it even allow loops and all forms of arithmetic etc? I have not learned it myself, and nor will i, because why? Because javascript is so convenient, and allows me to do whatever i want. It is also the same language I use when writing the dapp back-ends, and can even be integrated with other dapp tests (let's say i want to do that test as part of a suite that includes ipfs, legal markdown and other things). 

If EPM can go without a test contract in the case I laid out here, then it's reading return values directly, which is not supported by all clients. Does that even work with go-eth? When that is a common thing, and you can expect all clients to do it, then we should include support for it, definitely, but that puts this system at par with epm anyways in terms of what contracts you need.

Either way, both this and "epm cli is better" are none issues, because those that want can still do that. It doesn't take any of the powers away from epm.

In regards to (2) - I'm not sure exactly what you're saying. "Classes" is exactly what these specs are. They are used to define the contract in an external environment, so that the contracts can be communicated with from that environment. It will be possible to compose specs from dependencies too, making inheritance possible. That is written somewhere in the post. When getting return values are supported, knowing the types of those values will be useful, so that's why I'm putting them in there now.

When it comes to "storage types", what the types will do is allow the external environment, whatever it may be, to read from contract storage and get the data on the proper form. If it's supposed to be an object of some type, or an element of a list (which could be an object too i guess), then that's what you get - the equivalent javascript (or json) representation of that object. The 'Type' that can be specified for variables in the spec will definitely allow composite types as well. There will be a whole lot of stuff in there! You'll do the actual reads by using action models (which i haven't gotten into yet), but they'd be very similar to the PD ones. The read will return an object, an array, a string or a number, depending on the type. Objecs will be used for composite types, which could be anything. Even contracts should be allowed to be types imo.

When it comes to the variables in the specs: They don't have to specify storage addresses by using the hex string. They could use an ascii string if they like that better, but this is a very good point. In fact, the reading function should assume that if the address does not have an 0x in front, it's ascii. That should be the convention.

Finally, nobody should be restricted by this. Just like they're free to not use a RESTful api for their dapps, they're free to use whatever conventions they like when it comes to contract deployment, interaction, and testing. The only thing they have to stick to is the blockchain API methods. None of this is supposed to be mandatory. It's just a way to help people get past the 15 different systems, 15 different languages and 15 different tools paradigm, and making it easier to use our stuff. It's creating a standard, much like REST will be the standard for HTTP, and 'whatever' will be the standard for websockets (pretty sure David and Jake will bring something that's better then the 'ESRPC' protocol i drafted).

It'll be a lot clearer when some actual code is in place.

**Comment by dennismckinnon** [comment] 2015-01-25 06:44
EPM is a non-issue like you say. And I agree its not perfect. If you make "command line" access into ate so i can write unit tests and what not for a decerver version of EPM then great. I will be happy to use it. Currently as it stands the decerver is not a good tool for testing with. Every time you want to run a test you have to reboot the decerver? there needs to be an easier way. You make it I'll use it happily.

Maybe we have our wires crossed with respect to these specs. When I see you list a slot by an explicit address be it in hex or in ascii what I see is far too restrictive format. Partitioning storage addresses into complex types requires arithmetic. While I could write in the name (which can give you a partition of the variable space) and the type (which is unecessary since the variables are self defining) it would be completely meaningless because the structure of the storage is more then a single slot. Its a set of rules for how to obtain the slots and what they mean. I don't see how you can capture those rules in a json. thats why they the models for reading them are written in full js. You could come up with template json objects which you could pull out but I don't think this is a scalable solution in general. I may be wrong but it sounds like you want to read the entire linked list into memory or potentially an entire indexing table. What if we have a dapp with a million users (suppose its youtube) a single user requires I believe 128 bytes so the list of user accounts is 128 MB. not so bad i suppose. But thats JUST usernames and account contracts. What if its the indexing table for video tags. its not hard to imagine that being a couple gigabytes at the very least. possibly more. suddenly running a dapp causes most computers to jump to swap. 

I'm not trying to be obstinant.I'm sure I'm missing something I just don't understand how "getElement" as a generic access method is going to function because some of these things might not end up being that small. I agree there is a need for this. Just trying to understand how this could actually work.

**Comment by androlo** [comment] 2015-01-25 09:44
This has to happen. We need to drop the old crap asap and get with the program. No need for serpent at all imo, but rather go with Solidity all the way.

Btw. Dennis i think you would be excited about Solidity. It has language support for some of the stuff you want, such as hashing variables in order to auto allocate storage addresses (it does that in some cases). By the looks of it, it does some of what the esl contracts does, but without the hard coded memory addresses, double-storage slots for variables etc. Also, there is apparently no need to specify variable addresses at all - instead it should just be variable name and type pairs. I think actually it would be possible to have a single storage read function for everything. It looks sort of like what I imagined douglang would have eventually become.

I can't say that this will be good for the gendoug stuff, since I don't know exactly how that's written, but I imagine you could replace variables with simple structs that has two variables in them, one for the actual data, and one for the permissions and whatever else you need to put in there. Should be pretty straight forward.

Solidity + epm + ate will kill it. It will be the ultimate contract developement, execution and testing environment, no doubts.

**Comment by androlo** [comment] 2015-01-25 11:39
Also, don't worry. This will not really affect you, if implemented, so you won't have to use any of it. I don't know what you and Ethan are doing with gendoug, or what y'all need, and I don't pretend that I do. This is just the early stages of a push to make DApp making easier. Anyone would still be free to use their tools and whatever languages they see fit.

Btw, not only should the contract language and supporting infrastructure be updated, there should also be an update in the way dapp contract systems are viewed. DApps shouldn't be designed starting with the contracts imo. DApps has a backend javascript and a UI component as well, and they all go together, so I think DApp contract systems should be developed with that in mind and be subservient to the over-all design rather then dictating it. In fact, it will most likely be good to use data/action models to prototype the contracts (and the entire system) before actually starting to code it. Integration...

When it comes to those flimsy specs in post 1 - they are super basic examples of how it could be done, and I'm pretty sure I point that out. The real important part i think is that they do not contain any actual logic. The action models is what will do the heavy lifting. They're javascript specific, though, but the design I'm going to propose is pretty much the same as the project douglas action models system, but adapted to having a javascript vm at hand, and some other new systems - and also some new C3D stuff. The main difference i guess is that they're always, 100% of the time based on a spec, or data model, and that they run javascript instead of the script that was used before (this is actually what ate was originally supposed to do - pd action models and nothing else).

**Comment by androlo** [comment] 2015-01-25 11:53
I don't think Ate should provide command line access to epm. That would make little sense imo. It should do two things:

1 - use it to create, remove, and switch between chains.

2 - leverage its multi-client support to interact with different blockchains, rather then using one module for each like we do now. Just load the chain you want into epm and have at it. :D

**Comment by compleatang** [comment] 2015-01-25 12:13
@androlo I'm roughly in agreement here. 

Caveat 1: 

I think it makes sense for Ate to have access to EPM. This will eventually help in chain birthing, but for now it can help us primarily from monkAdmin (which needs a reboot immediately after DApp1 pushed). It would be imminently helpful to drop to the bottom of monkAdmin and have access to EPM from there.

Caveat 2:

The tests we are talking about here are stack integration tests. They aren't really unit tests for contracts. Those should probably stay happening within the .pdt. However, the .pdt is suboptimal for anything beyond unit tests. I don't see a need to move beyond simple unit tests in .pdt because we have enough that we can (and need) to do at that level. We don't want EPM to have an Ate instance so even if we move .pdt and .pdx to YAML that doesn't really solve the issue that you're talking about. 

I think the testing framework you are referring to here is more viable for integration tests -- and so it is `apples` to `oranges` with .pdt's. It is also essential for attack vector scripting and the like which should happen from the Ate level as we've discussed to leverage the scripting capabilities of js. Seems to me if we think of this issue in that light that the slight differences expressed above fade away.

**Comment by androlo** [comment] 2015-01-25 14:38
I think also that ate should have access to epm but actually in the form of a module, not just cli, but I think you're right. I figured it would be possible to bind all the blockchains to epm instead of having a module for each, since it can load many blockchain clients, but then I guess it would be weird if you want to run both monk and eth, for example.

It is true that a pdt or pdx is faster to run, and probably more convenient in many ways, but it is not necessarily harder or less reliable to do them in ate, and I think the pros will eventually outweigh the cons. A javascript file would be just as simple to write as a pdt or pdx, if not simpler, and works with the exact same chain api. You wouldn't have to learn a whole new language for doing contract deployment and tests; instead you'd use the same well-known language you used for all other tests - which is also the same language you use when interacting with these contracts in your normal code. It would also be very versatile. For example, can pdt files run script in other pdt files as part of a full test suite, or wrap tests (or parts of them) into functions that takes parameters and can be used in many different tests, as well as in other code? And can they be included seamlessly in full stack integration tests? Maybe so, but these things are also possible in ate. In fact they're all trivial.

Besides, people will write dapp tests in js, and if they do full stack integration tests, which basically means doing a bunch of calls to the different module apis, sooner or later they will discover that doing contract tests in js works just as well as doing them in pdt. I find it hard to believe that when that happens they'd just continue to use pdt/pdx for contracts and js for the rest, and not just make them all in the same way. 

Seriously... pdx, pdt, douglang, anything else we might start using, it's always gonna be just a matter of time before it gets "wal-marted" by ate and its javascript. There really is no escape. I've already come to terms with it.

**Comment by compleatang** [comment] 2015-01-25 14:40
> There really is no escape. I've already come to terms with it.

**Comment by androlo** [comment] 2015-01-25 16:07
ok

**Comment by androlo** [comment] 2015-01-25 18:09
https://github.com/ethereum/ethereum.js/blob/master/example/contract.html

Apparently, json contract definition specs is something that ethereum.js uses as well. Gonna look into it more. If it's broad enough we could maybe use the same one.

**Comment by androlo** [comment] 2015-01-25 18:39
https://github.com/ethereum/wiki/wiki/Ethereum-Contract-ABI

Lots of updates going on.

**Comment by androlo** [comment] 2015-01-25 18:50
They are all encoded in big-endian, padded to a multiple of 32 bytes. Negative values (for signed types) are padded with ones on the higher-oder side, non-negative values and unsigned types with zeros. String types are padded with zeros on the lower-order side.

hahahaha ok...

**Comment by ebuchman** [comment] 2015-01-25 21:39
So I think I agree with most of this.  EPM pdx/pdt environment is supposed to be for dead simple integration tests, without having to fuss with writing any javascript and setting up an ate instance. We could add an ate instance to epm and bind the blockchain that's being tested, and write the tests in js, and thats probably fine too. 

The LLLC-server provides language agnostic compilation of contract suites just be specifying a regex for "include". As soon as I manage to compile solidity, it will be supported, and we can start moving towards it in all our examples and everything and possibly for gendoug.

**Comment by compleatang** [comment] 2015-03-13 13:01
deprecating this issue in favor of decerver-node + epm serve upcoming work.

**Closed by compleatang** 2015-03-13 13:01 UTC
Labels: design, ideas for review
