### ISSUE TITLE
script_windows.go

### ISSUE THREAD

**Issue by jdevoo** [eris-ltd/decerver#88] opened 2015-01-16 18:35 UTC
I am compiling decever under mingw and am stuck at script_windows.go with `compiler := mutan.NewCompiler(backend.NewTheloniousBackend())` 
`backend.NewTheloniousBackend()` is undefined.

**Comment by jdevoo** [comment] 2015-01-16 18:51
My setup is as follows: Go 1.4 for windows, hg for windows 3.2.4, mingw32 from the Cygwin packages, gmp 6.0 compiled with mingw32 and installed under /usr/local. My Go environment is as follows
    set GOARCH=386
    set GOBIN=
    set GOCHAR=8
    set GOEXE=.exe
    set GOHOSTARCH=386
    set GOHOSTOS=windows
    set GOOS=windows
    set GOPATH=C:\GoWorkspace
    set GORACE=
    set GOROOT=C:\Go
    set GOTOOLDIR=C:\Go\pkg\tool\windows_386
    set CC=i686-pc-mingw32-gcc
    set GOGCCFLAGS=-m32 -mthreads -fmessage-length=0
    set CXX=i686-pc-mingw32-g++
    set CGO_ENABLED=1
In addition, I set `CGO_CFLAGS="-I/usr/local/include"` and "CGO_LDFLAGS="-L/usr/local/lib"`

**Comment by androlo** [comment] 2015-01-16 21:15
Yes this is caused by build directives in thelonious/monkutil/script.go and script_windows.go. It's loading a different script depending on os. it's easy to fix but i would not recommend building on windows anyways. we're looking into the ecc lib, and some other stuff. thel is not win compatible as of now. installers has been postponed until we pushed some dapps. id just wait for those.

**Comment by androlo** [comment] 2015-01-16 21:20
i'll close this and open up a win compat issue in the thel repo, and reference this. it might as well stay up until we've dealt with it.

**Comment by androlo** [comment] 2015-01-16 21:25
the new one: https://github.com/eris-ltd/thelonious/issues/75

**Comment by dennismckinnon** [comment] 2015-01-16 22:48
Actually jdevoo if you can get this running please let us know. We dont have time to pursue this right now but if you can get it running let us know what you had to do. We will work on improving windows compatibilty but like andreas said there are some complicating factors. 

If you do have to make changes to get it to work please track and maybe even pull request them.

**Comment by androlo** [comment] 2015-01-16 22:49
there's a new issue in the thel repo. it's referenced right above your post.

**Closed by androlo** 2015-01-16 22:49 UTC

**Comment by compleatang** [comment] 2015-03-28 11:32
To be clear, at this time we are unable to support Windows. Windows OS support is on our ToDo list, but at this point it is very low priority because of how easy vagrant // docker make it to work within containers and/or a vm. 

If folks are interested in helping on Windows we'd love some assistance as we are a small team. As they say: PR's welcome!
